// Code generated by opq. DO NOT EDIT.

package meta

import "strings"

func GetPermissions(permissions Permission) string {
	permissionsStr := []string{}
	if permissions&GroupRevokePermission != 0 {
		permissionsStr = append(permissionsStr, "撤回群消息权限")
	}
	if permissions&GroupMemberBanPermission != 0 {
		permissionsStr = append(permissionsStr, "禁言群成员权限")
	}
	if permissions&ReceiveFriendMsgPermission != 0 {
		permissionsStr = append(permissionsStr, "接收好友消息事件权限")
	}
	if permissions&SendGroupMsgPermission != 0 {
		permissionsStr = append(permissionsStr, "发送群消息权限")
	}
	if permissions&HTTPRequestPermission != 0 {
		permissionsStr = append(permissionsStr, "[⚠️注意] Http联网权限")
	}
	if permissions&GetPSeyPermission != 0 {
		permissionsStr = append(permissionsStr, "[⚠️注意] 获取 PS Key 权限")
	}
	if permissions&GetGroupMemberListPermission != 0 {
		permissionsStr = append(permissionsStr, "获取群成员列表权限")
	}
	if permissions&UploadPermission != 0 {
		permissionsStr = append(permissionsStr, "上传文件权限")
	}
	if permissions&GroupMemberRemovePermission != 0 {
		permissionsStr = append(permissionsStr, "踢出群组成员权限")
	}
	if permissions&RemoteCallEventPermission != 0 {
		permissionsStr = append(permissionsStr, "[⚠️注意] 远程调用接口权限")
	}
	if permissions&GetGroupListPermission != 0 {
		permissionsStr = append(permissionsStr, "获取群列表权限")
	}
	if permissions&ReceivePrivateMsgPermission != 0 {
		permissionsStr = append(permissionsStr, "接收私聊消息事件权限")
	}
	if permissions&RegisterCronEventPermission != 0 {
		permissionsStr = append(permissionsStr, "添加注册周期定时任务权限")
	}
	if permissions&SendFriendMsgPermission != 0 {
		permissionsStr = append(permissionsStr, "发送好友消息权限")
	}
	if permissions&SendPrivateChatMsgPermission != 0 {
		permissionsStr = append(permissionsStr, "发送私聊权限")
	}
	if permissions&RegisterMiddlePermission != 0 {
		permissionsStr = append(permissionsStr, "注册中间件权限")
	}
	if permissions&GetFriendListPermission != 0 {
		permissionsStr = append(permissionsStr, "获取好友列表权限")
	}
	if permissions&GetClientKeyPermission != 0 {
		permissionsStr = append(permissionsStr, "[⚠️注意] 获取 Client Key 权限")
	}
	if permissions&ReceiveGroupMsgPermission != 0 {
		permissionsStr = append(permissionsStr, "接收群消息事件权限")
	}
	if permissions&SystemInfoPermission != 0 {
		permissionsStr = append(permissionsStr, "获取系统信息权限")
	}
	return strings.Join(permissionsStr, "\n")
}
func SumPermissions(permissions ...string) Permission {
	var sum Permission = 0
	for _, v := range permissions {
		switch v {
		case "GroupRevokePermission":
			sum |= GroupRevokePermission
		case "GroupMemberBanPermission":
			sum |= GroupMemberBanPermission
		case "ReceiveFriendMsgPermission":
			sum |= ReceiveFriendMsgPermission
		case "AllPermission":
			sum |= AllPermission
		case "SendGroupMsgPermission":
			sum |= SendGroupMsgPermission
		case "HTTPRequestPermission":
			sum |= HTTPRequestPermission
		case "GetPSeyPermission":
			sum |= GetPSeyPermission
		case "GetGroupMemberListPermission":
			sum |= GetGroupMemberListPermission
		case "UploadPermission":
			sum |= UploadPermission
		case "GroupMemberRemovePermission":
			sum |= GroupMemberRemovePermission
		case "RemoteCallEventPermission":
			sum |= RemoteCallEventPermission
		case "GroupAdminPermission":
			sum |= GroupAdminPermission
		case "GetGroupListPermission":
			sum |= GetGroupListPermission
		case "ReceivePrivateMsgPermission":
			sum |= ReceivePrivateMsgPermission
		case "RegisterCronEventPermission":
			sum |= RegisterCronEventPermission
		case "ReceiveAllMsgPermission":
			sum |= ReceiveAllMsgPermission
		case "SendFriendMsgPermission":
			sum |= SendFriendMsgPermission
		case "SendPrivateChatMsgPermission":
			sum |= SendPrivateChatMsgPermission
		case "RegisterMiddlePermission":
			sum |= RegisterMiddlePermission
		case "GetFriendListPermission":
			sum |= GetFriendListPermission
		case "GetClientKeyPermission":
			sum |= GetClientKeyPermission
		case "ReceiveGroupMsgPermission":
			sum |= ReceiveGroupMsgPermission
		case "SystemInfoPermission":
			sum |= SystemInfoPermission
		case "SendMsgPermission":
			sum |= SendMsgPermission
		}
	}
	return sum
}
