// Code generated by protoc-gen-go-plugin. DO NOT EDIT.
// versions:
// 	protoc-gen-go-plugin v0.1.0
// 	protoc               v3.19.4
// source: proto/opq.proto

package proto

import (
	context "context"
	emptypb "github.com/knqyf263/go-plugin/types/known/emptypb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogType int32

const (
	LogType_Debug LogType = 0
	LogType_Info  LogType = 1
	LogType_Warn  LogType = 2
	LogType_Error LogType = 3
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "Debug",
		1: "Info",
		2: "Warn",
		3: "Error",
	}
	LogType_value = map[string]int32{
		"Debug": 0,
		"Info":  1,
		"Warn":  2,
		"Error": 3,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

type HttpMethod int32

const (
	HttpMethod_GET    HttpMethod = 0
	HttpMethod_POST   HttpMethod = 1
	HttpMethod_PUT    HttpMethod = 2
	HttpMethod_DELETE HttpMethod = 3
)

// Enum value maps for HttpMethod.
var (
	HttpMethod_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
	}
	HttpMethod_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
	}
)

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

type UploadId int32

const (
	UploadId_Group  UploadId = 0
	UploadId_Friend UploadId = 1
)

// Enum value maps for UploadId.
var (
	UploadId_name = map[int32]string{
		0: "Group",
		1: "Friend",
	}
	UploadId_value = map[string]int32{
		"Group":  0,
		"Friend": 1,
	}
)

func (x UploadId) Enum() *UploadId {
	p := new(UploadId)
	*p = x
	return p
}

type RemoteCallReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcPluginName string `protobuf:"bytes,1,opt,name=srcPluginName,proto3" json:"srcPluginName,omitempty"`
	DstPluginName string `protobuf:"bytes,2,opt,name=dstPluginName,proto3" json:"dstPluginName,omitempty"`
	CallPath      string `protobuf:"bytes,3,opt,name=callPath,proto3" json:"callPath,omitempty"`
	Args          []byte `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"`
}

func (x *RemoteCallReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RemoteCallReq) GetSrcPluginName() string {
	if x != nil {
		return x.SrcPluginName
	}
	return ""
}

func (x *RemoteCallReq) GetDstPluginName() string {
	if x != nil {
		return x.DstPluginName
	}
	return ""
}

func (x *RemoteCallReq) GetCallPath() string {
	if x != nil {
		return x.CallPath
	}
	return ""
}

func (x *RemoteCallReq) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type RemoteCallReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RemoteCallReply) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *RemoteCallReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CronEventReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CronEventReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CronEventReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type InitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 是否初始化成功？
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// 初始化失败信息
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *InitReply) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *InitReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InitReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommonMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time        int64  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`               // 消息发送的时间戳
	SelfId      int64  `protobuf:"varint,2,opt,name=selfId,proto3" json:"selfId,omitempty"`           // 机器人QQ号
	FromUin     int64  `protobuf:"varint,3,opt,name=fromUin,proto3" json:"fromUin,omitempty"`         // 消息来源 ID
	SenderUin   int64  `protobuf:"varint,4,opt,name=senderUin,proto3" json:"senderUin,omitempty"`     // 消息来源 ID
	Message     string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`          // 消息内容
	RawMessage  []byte `protobuf:"bytes,6,opt,name=rawMessage,proto3" json:"rawMessage,omitempty"`    // 原始消息
	MessageId   int32  `protobuf:"varint,7,opt,name=messageId,proto3" json:"messageId,omitempty"`     // 消息ID
	MessageType int32  `protobuf:"varint,8,opt,name=messageType,proto3" json:"messageType,omitempty"` // 消息类型
}

func (x *CommonMsg) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CommonMsg) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *CommonMsg) GetSelfId() int64 {
	if x != nil {
		return x.SelfId
	}
	return 0
}

func (x *CommonMsg) GetFromUin() int64 {
	if x != nil {
		return x.FromUin
	}
	return 0
}

func (x *CommonMsg) GetSenderUin() int64 {
	if x != nil {
		return x.SenderUin
	}
	return 0
}

func (x *CommonMsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonMsg) GetRawMessage() []byte {
	if x != nil {
		return x.RawMessage
	}
	return nil
}

func (x *CommonMsg) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *CommonMsg) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

type CronJob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Spec string `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *CronJob) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *CronJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LogReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogType LogType `protobuf:"varint,1,opt,name=logType,proto3,enum=proto.LogType" json:"logType,omitempty"`
	Msg     string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *LogReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *LogReq) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_Debug
}

func (x *LogReq) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type HttpReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method  HttpMethod        `protobuf:"varint,2,opt,name=method,proto3,enum=proto.HttpMethod" json:"method,omitempty"`
	Header  map[string]string `protobuf:"bytes,3,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Content []byte            `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *HttpReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HttpReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpReq) GetMethod() HttpMethod {
	if x != nil {
		return x.Method
	}
	return HttpMethod_GET
}

func (x *HttpReq) GetHeader() map[string]string {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HttpReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type HttpRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header     string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	StatusCode int32  `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Content    []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *HttpRes) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *HttpRes) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *HttpRes) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpRes) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type TextMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextMsg) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *TextMsg) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileId    int64  `protobuf:"varint,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	FileMd5   string `protobuf:"bytes,2,opt,name=fileMd5,proto3" json:"fileMd5,omitempty"`
	FileSize  int32  `protobuf:"varint,3,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	FileToken string `protobuf:"bytes,4,opt,name=fileToken,proto3" json:"fileToken,omitempty"`
}

func (x *File) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *File) GetFileId() int64 {
	if x != nil {
		return x.FileId
	}
	return 0
}

func (x *File) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *File) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *File) GetFileToken() string {
	if x != nil {
		return x.FileToken
	}
	return ""
}

type Files struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []*File `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
}

func (x *Files) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *Files) GetFile() []*File {
	if x != nil {
		return x.File
	}
	return nil
}

type JsonMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Json string `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
}

func (x *JsonMsg) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *JsonMsg) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type XmlMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xml string `protobuf:"bytes,1,opt,name=xml,proto3" json:"xml,omitempty"`
}

func (x *XmlMsg) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *XmlMsg) GetXml() string {
	if x != nil {
		return x.Xml
	}
	return ""
}

type MsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUin int64 `protobuf:"varint,1,opt,name=toUin,proto3" json:"toUin,omitempty"`
	// Types that are assignable to Msg:
	//
	//	*MsgReq_TextMsg
	//	*MsgReq_PicMsg
	//	*MsgReq_XmlMsg
	//	*MsgReq_JsonMsg
	Msg       isMsgReq_Msg `protobuf_oneof:"msg"`
	AtUin     []int64      `protobuf:"varint,3,rep,packed,name=atUin,proto3" json:"atUin,omitempty"`
	BotUin    int64        `protobuf:"varint,4,opt,name=botUin,proto3" json:"botUin,omitempty"`
	GroupCode *int64       `protobuf:"varint,9,opt,name=groupCode,proto3,oneof" json:"groupCode,omitempty"`
}

func (x *MsgReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *MsgReq) GetToUin() int64 {
	if x != nil {
		return x.ToUin
	}
	return 0
}

func (m *MsgReq) GetMsg() isMsgReq_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *MsgReq) GetTextMsg() *TextMsg {
	if x, ok := x.GetMsg().(*MsgReq_TextMsg); ok {
		return x.TextMsg
	}
	return nil
}

func (x *MsgReq) GetPicMsg() *Files {
	if x, ok := x.GetMsg().(*MsgReq_PicMsg); ok {
		return x.PicMsg
	}
	return nil
}

func (x *MsgReq) GetXmlMsg() *XmlMsg {
	if x, ok := x.GetMsg().(*MsgReq_XmlMsg); ok {
		return x.XmlMsg
	}
	return nil
}

func (x *MsgReq) GetJsonMsg() *JsonMsg {
	if x, ok := x.GetMsg().(*MsgReq_JsonMsg); ok {
		return x.JsonMsg
	}
	return nil
}

func (x *MsgReq) GetAtUin() []int64 {
	if x != nil {
		return x.AtUin
	}
	return nil
}

func (x *MsgReq) GetBotUin() int64 {
	if x != nil {
		return x.BotUin
	}
	return 0
}

func (x *MsgReq) GetGroupCode() int64 {
	if x != nil && x.GroupCode != nil {
		return *x.GroupCode
	}
	return 0
}

type isMsgReq_Msg interface {
	isMsgReq_Msg()
}

type MsgReq_TextMsg struct {
	TextMsg *TextMsg `protobuf:"bytes,5,opt,name=textMsg,proto3,oneof"`
}

type MsgReq_PicMsg struct {
	PicMsg *Files `protobuf:"bytes,6,opt,name=picMsg,proto3,oneof"`
}

type MsgReq_XmlMsg struct {
	XmlMsg *XmlMsg `protobuf:"bytes,7,opt,name=xmlMsg,proto3,oneof"`
}

type MsgReq_JsonMsg struct {
	JsonMsg *JsonMsg `protobuf:"bytes,8,opt,name=jsonMsg,proto3,oneof"`
}

func (*MsgReq_TextMsg) isMsgReq_Msg() {}

func (*MsgReq_PicMsg) isMsgReq_Msg() {}

func (*MsgReq_XmlMsg) isMsgReq_Msg() {}

func (*MsgReq_JsonMsg) isMsgReq_Msg() {}

type SendReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32   `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	ErrMsg *string `protobuf:"bytes,2,opt,name=ErrMsg,proto3,oneof" json:"ErrMsg,omitempty"`
}

func (x *SendReply) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *SendReply) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *SendReply) GetErrMsg() string {
	if x != nil && x.ErrMsg != nil {
		return *x.ErrMsg
	}
	return ""
}

type UploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to File:
	//
	//	*UploadReq_Path
	//	*UploadReq_Url
	//	*UploadReq_Base64Buf
	File     isUploadReq_File `protobuf_oneof:"file"`
	BotUin   int64            `protobuf:"varint,4,opt,name=botUin,proto3" json:"botUin,omitempty"`
	UploadId UploadId         `protobuf:"varint,5,opt,name=uploadId,proto3,enum=proto.UploadId" json:"uploadId,omitempty"`
}

func (x *UploadReq) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (m *UploadReq) GetFile() isUploadReq_File {
	if m != nil {
		return m.File
	}
	return nil
}

func (x *UploadReq) GetPath() string {
	if x, ok := x.GetFile().(*UploadReq_Path); ok {
		return x.Path
	}
	return ""
}

func (x *UploadReq) GetUrl() string {
	if x, ok := x.GetFile().(*UploadReq_Url); ok {
		return x.Url
	}
	return ""
}

func (x *UploadReq) GetBase64Buf() string {
	if x, ok := x.GetFile().(*UploadReq_Base64Buf); ok {
		return x.Base64Buf
	}
	return ""
}

func (x *UploadReq) GetBotUin() int64 {
	if x != nil {
		return x.BotUin
	}
	return 0
}

func (x *UploadReq) GetUploadId() UploadId {
	if x != nil {
		return x.UploadId
	}
	return UploadId_Group
}

type isUploadReq_File interface {
	isUploadReq_File()
}

type UploadReq_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"`
}

type UploadReq_Url struct {
	Url string `protobuf:"bytes,2,opt,name=url,proto3,oneof"`
}

type UploadReq_Base64Buf struct {
	Base64Buf string `protobuf:"bytes,3,opt,name=base64buf,proto3,oneof"`
}

func (*UploadReq_Path) isUploadReq_File() {}

func (*UploadReq_Url) isUploadReq_File() {}

func (*UploadReq_Base64Buf) isUploadReq_File() {}

type UploadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32   `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	ErrMsg *string `protobuf:"bytes,2,opt,name=ErrMsg,proto3,oneof" json:"ErrMsg,omitempty"`
	File   *File   `protobuf:"bytes,3,opt,name=file,proto3,oneof" json:"file,omitempty"`
}

func (x *UploadReply) ProtoReflect() protoreflect.Message {
	panic(`not implemented`)
}

func (x *UploadReply) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *UploadReply) GetErrMsg() string {
	if x != nil && x.ErrMsg != nil {
		return *x.ErrMsg
	}
	return ""
}

func (x *UploadReply) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

// go:plugin type=plugin version=1
type Event interface {
	// 插件初始化
	Init(context.Context, *emptypb.Empty) (*InitReply, error)
	// 群消息
	OnGroupMsg(context.Context, *CommonMsg) (*emptypb.Empty, error)
	// 好友消息
	OnFriendMsg(context.Context, *CommonMsg) (*emptypb.Empty, error)
	// 私聊消息
	OnPrivateMsg(context.Context, *CommonMsg) (*emptypb.Empty, error)
	// 插件卸载 保存资料 最大等待 2s
	Unload(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// 周期任务唤醒
	OnCronEvent(context.Context, *CronEventReq) (*emptypb.Empty, error)
	// 其他插件调用本插件事件
	OnRemoteCallEvent(context.Context, *RemoteCallReq) (*RemoteCallReply, error)
}

// go:plugin type=host
type Api interface {
	Log(context.Context, *LogReq) (*emptypb.Empty, error)
	Http(context.Context, *HttpReq) (*HttpRes, error)
	SendGroupMsg(context.Context, *MsgReq) (*SendReply, error)
	SendFriendMsg(context.Context, *MsgReq) (*SendReply, error)
	SendPrivateMsg(context.Context, *MsgReq) (*SendReply, error)
	Upload(context.Context, *UploadReq) (*UploadReply, error)
	RegisterCronJob(context.Context, *CronJob) (*emptypb.Empty, error)
	RemoveCronJob(context.Context, *CronJob) (*emptypb.Empty, error)
	// 调用其他插件功能
	RemoteCall(context.Context, *RemoteCallReq) (*RemoteCallReply, error)
}
