name: release

on:
  push:
    branches:
      - 'master'
      - 'beta'
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (No "v")'
        required: true
        type: string
  pull_request:
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      -
        name: Tests
        run: |
          go mod tidy
          go test -v ./...
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: "v1.17.2"
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}